Feat: move injection equipment into windows dll
factorio-rivets/rivets-factorio-mod pull request #3
Opened 2024-08-12 19:40 UTC by notnotmelon

2024-08-13 02:08 UTC, fgardt requested changes
I think it might make sense to expand this PR to be fully cross platform? Should not be too much that needs to be moved / annotated with cfg to get it to compile on https://github.com/factorio-rivets/rivets-factorio-mod/labels/os%3A%3Alinux. \
`libloading` and all the parts providing it with binaries & paths are already cross platform so there should not be much work (if any) to get it functional once it actually compiles :)

2024-08-13 02:08 UTC, fgardt commented on src/lib.rs
> +    let mod_list = ModList::generate_custom(read_data, &write_data)?;
Fixing the issue that caused injector to not find mods. Also run `cargo update` to get an updated version of `mod_util`
```suggestion
    let mut mod_list = ModList::generate_custom(read_data, &write_data)?;
    mod_list.load();
```

2024-08-13 02:08 UTC, fgardt commented on src/lib.rs
> +    }
I feel like the `factorio_` prefix is a bit verbose and not needed?

```suggestion
    for mod_name in mod_load_order {
        let current_mod = all_active_mods
            .get(&mod_name)
            .expect("The list of active mods contains all mods in the load order");

        let lib = match current_mod.get_file(RIVETS_LIB) {
            Err(ModError::PathDoesNotExist(_)) => continue,
            Ok(lib) => lib,
            Err(e) => return Err(e.into()),
        };

        std::fs::create_dir_all(write_data.as_ref().join("temp/rivets"))?;

        let extracted_lib_name = format!("{mod_name}{DYNAMIC_LIBRARY_SUFFIX}");
        let lib_path = write_data
            .as_ref()
            .join("temp/rivets")
            .join(extracted_lib_name);
        std::fs::write(&lib_path, lib)?;

        result.push(lib_path);
    }
```

2024-08-13 02:08 UTC, fgardt commented on src/lib.rs
>      let factorio_path = std::path::Path::new("C:/Users/zacha/Documents/factorio/bin");
hardcoded path? :)

2024-08-13 02:08 UTC, fgardt commented on src/lib.rs
> +        let rivets_finalize_abi = &*rivets_finalize_abi();
?

2024-08-14 06:56 UTC, fgardt approved these changes
LGTM

2024-08-15 02:26 UTC, notnotmelon commented
This still needs more work, sorry

2024-08-15 21:18 UTC, merged